#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bailam1.Models.LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="data_QLSV")]
	public partial class DataQLSVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLOP(LOP instance);
    partial void UpdateLOP(LOP instance);
    partial void DeleteLOP(LOP instance);
    partial void InsertDM_TONGIAO(DM_TONGIAO instance);
    partial void UpdateDM_TONGIAO(DM_TONGIAO instance);
    partial void DeleteDM_TONGIAO(DM_TONGIAO instance);
    partial void InsertDM_QUEQUAN(DM_QUEQUAN instance);
    partial void UpdateDM_QUEQUAN(DM_QUEQUAN instance);
    partial void DeleteDM_QUEQUAN(DM_QUEQUAN instance);
    partial void InsertDM_DANTOC(DM_DANTOC instance);
    partial void UpdateDM_DANTOC(DM_DANTOC instance);
    partial void DeleteDM_DANTOC(DM_DANTOC instance);
    partial void InsertDM_KHOA(DM_KHOA instance);
    partial void UpdateDM_KHOA(DM_KHOA instance);
    partial void DeleteDM_KHOA(DM_KHOA instance);
    partial void InsertDM_NIENKHOA(DM_NIENKHOA instance);
    partial void UpdateDM_NIENKHOA(DM_NIENKHOA instance);
    partial void DeleteDM_NIENKHOA(DM_NIENKHOA instance);
    partial void InsertSINHVIEN(SINHVIEN instance);
    partial void UpdateSINHVIEN(SINHVIEN instance);
    partial void DeleteSINHVIEN(SINHVIEN instance);
    #endregion
		
		public DataQLSVDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["data_QLSVConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLSVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLSVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLSVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLSVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LOP> LOPs
		{
			get
			{
				return this.GetTable<LOP>();
			}
		}
		
		public System.Data.Linq.Table<DM_TONGIAO> DM_TONGIAOs
		{
			get
			{
				return this.GetTable<DM_TONGIAO>();
			}
		}
		
		public System.Data.Linq.Table<DM_QUEQUAN> DM_QUEQUANs
		{
			get
			{
				return this.GetTable<DM_QUEQUAN>();
			}
		}
		
		public System.Data.Linq.Table<DM_DANTOC> DM_DANTOCs
		{
			get
			{
				return this.GetTable<DM_DANTOC>();
			}
		}
		
		public System.Data.Linq.Table<DM_CHUYENNGANH_THEO_KHOA> DM_CHUYENNGANH_THEO_KHOAs
		{
			get
			{
				return this.GetTable<DM_CHUYENNGANH_THEO_KHOA>();
			}
		}
		
		public System.Data.Linq.Table<DM_KHOA> DM_KHOAs
		{
			get
			{
				return this.GetTable<DM_KHOA>();
			}
		}
		
		public System.Data.Linq.Table<DM_NIENKHOA> DM_NIENKHOAs
		{
			get
			{
				return this.GetTable<DM_NIENKHOA>();
			}
		}
		
		public System.Data.Linq.Table<SINHVIEN> SINHVIENs
		{
			get
			{
				return this.GetTable<SINHVIEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOP")]
	public partial class LOP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaLop;
		
		private string _TenLop;
		
		private string _MaChuyenNganh;
		
		private string _MaKhoa;
		
		private string _MaNienKhoa;
		
		private string _NguoiThem;
		
		private string _NguoiSua;
		
		private System.Nullable<System.DateTime> _NgayThem;
		
		private System.Nullable<System.DateTime> _NgaySua;
		
		private System.Nullable<bool> _IsDelete;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    partial void OnMaChuyenNganhChanging(string value);
    partial void OnMaChuyenNganhChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnMaNienKhoaChanging(string value);
    partial void OnMaNienKhoaChanged();
    partial void OnNguoiThemChanging(string value);
    partial void OnNguoiThemChanged();
    partial void OnNguoiSuaChanging(string value);
    partial void OnNguoiSuaChanged();
    partial void OnNgayThemChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThemChanged();
    partial void OnNgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySuaChanged();
    partial void OnIsDeleteChanging(System.Nullable<bool> value);
    partial void OnIsDeleteChanged();
    #endregion
		
		public LOP()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(MAX)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenNganh", DbType="NVarChar(10)")]
		public string MaChuyenNganh
		{
			get
			{
				return this._MaChuyenNganh;
			}
			set
			{
				if ((this._MaChuyenNganh != value))
				{
					this.OnMaChuyenNganhChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenNganh = value;
					this.SendPropertyChanged("MaChuyenNganh");
					this.OnMaChuyenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNienKhoa", DbType="NVarChar(10)")]
		public string MaNienKhoa
		{
			get
			{
				return this._MaNienKhoa;
			}
			set
			{
				if ((this._MaNienKhoa != value))
				{
					this.OnMaNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaNienKhoa = value;
					this.SendPropertyChanged("MaNienKhoa");
					this.OnMaNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThem", DbType="NVarChar(50)")]
		public string NguoiThem
		{
			get
			{
				return this._NguoiThem;
			}
			set
			{
				if ((this._NguoiThem != value))
				{
					this.OnNguoiThemChanging(value);
					this.SendPropertyChanging();
					this._NguoiThem = value;
					this.SendPropertyChanged("NguoiThem");
					this.OnNguoiThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiSua", DbType="NVarChar(50)")]
		public string NguoiSua
		{
			get
			{
				return this._NguoiSua;
			}
			set
			{
				if ((this._NguoiSua != value))
				{
					this.OnNguoiSuaChanging(value);
					this.SendPropertyChanging();
					this._NguoiSua = value;
					this.SendPropertyChanged("NguoiSua");
					this.OnNguoiSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThem", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThem
		{
			get
			{
				return this._NgayThem;
			}
			set
			{
				if ((this._NgayThem != value))
				{
					this.OnNgayThemChanging(value);
					this.SendPropertyChanging();
					this._NgayThem = value;
					this.SendPropertyChanged("NgayThem");
					this.OnNgayThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySua
		{
			get
			{
				return this._NgaySua;
			}
			set
			{
				if ((this._NgaySua != value))
				{
					this.OnNgaySuaChanging(value);
					this.SendPropertyChanging();
					this._NgaySua = value;
					this.SendPropertyChanged("NgaySua");
					this.OnNgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit")]
		public System.Nullable<bool> IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this.OnIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsDelete = value;
					this.SendPropertyChanged("IsDelete");
					this.OnIsDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_SINHVIEN", Storage="_SINHVIENs", ThisKey="MaLop", OtherKey="MaLop")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_TONGIAO")]
	public partial class DM_TONGIAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTonGiao;
		
		private string _TenTonGiao;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTonGiaoChanging(int value);
    partial void OnMaTonGiaoChanged();
    partial void OnTenTonGiaoChanging(string value);
    partial void OnTenTonGiaoChanged();
    #endregion
		
		public DM_TONGIAO()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTonGiao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTonGiao
		{
			get
			{
				return this._MaTonGiao;
			}
			set
			{
				if ((this._MaTonGiao != value))
				{
					this.OnMaTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._MaTonGiao = value;
					this.SendPropertyChanged("MaTonGiao");
					this.OnMaTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTonGiao", DbType="NVarChar(MAX)")]
		public string TenTonGiao
		{
			get
			{
				return this._TenTonGiao;
			}
			set
			{
				if ((this._TenTonGiao != value))
				{
					this.OnTenTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TenTonGiao = value;
					this.SendPropertyChanged("TenTonGiao");
					this.OnTenTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_TONGIAO_SINHVIEN", Storage="_SINHVIENs", ThisKey="MaTonGiao", OtherKey="MaTonGiao")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_TONGIAO = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_TONGIAO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_QUEQUAN")]
	public partial class DM_QUEQUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQueQuan;
		
		private string _TenQueQuan;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQueQuanChanging(int value);
    partial void OnMaQueQuanChanged();
    partial void OnTenQueQuanChanging(string value);
    partial void OnTenQueQuanChanged();
    #endregion
		
		public DM_QUEQUAN()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQueQuan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaQueQuan
		{
			get
			{
				return this._MaQueQuan;
			}
			set
			{
				if ((this._MaQueQuan != value))
				{
					this.OnMaQueQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQueQuan = value;
					this.SendPropertyChanged("MaQueQuan");
					this.OnMaQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQueQuan", DbType="NVarChar(MAX)")]
		public string TenQueQuan
		{
			get
			{
				return this._TenQueQuan;
			}
			set
			{
				if ((this._TenQueQuan != value))
				{
					this.OnTenQueQuanChanging(value);
					this.SendPropertyChanging();
					this._TenQueQuan = value;
					this.SendPropertyChanged("TenQueQuan");
					this.OnTenQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_QUEQUAN_SINHVIEN", Storage="_SINHVIENs", ThisKey="MaQueQuan", OtherKey="MaQueQuan")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_QUEQUAN = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_QUEQUAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_DANTOC")]
	public partial class DM_DANTOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanToc;
		
		private string _TenDanToc;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanTocChanging(int value);
    partial void OnMaDanTocChanged();
    partial void OnTenDanTocChanging(string value);
    partial void OnTenDanTocChanged();
    #endregion
		
		public DM_DANTOC()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanToc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanToc
		{
			get
			{
				return this._MaDanToc;
			}
			set
			{
				if ((this._MaDanToc != value))
				{
					this.OnMaDanTocChanging(value);
					this.SendPropertyChanging();
					this._MaDanToc = value;
					this.SendPropertyChanged("MaDanToc");
					this.OnMaDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanToc", DbType="NVarChar(MAX)")]
		public string TenDanToc
		{
			get
			{
				return this._TenDanToc;
			}
			set
			{
				if ((this._TenDanToc != value))
				{
					this.OnTenDanTocChanging(value);
					this.SendPropertyChanging();
					this._TenDanToc = value;
					this.SendPropertyChanged("TenDanToc");
					this.OnTenDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_DANTOC_SINHVIEN", Storage="_SINHVIENs", ThisKey="MaDanToc", OtherKey="MaDanToc")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_DANTOC = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_DANTOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_CHUYENNGANH_THEO_KHOA")]
	public partial class DM_CHUYENNGANH_THEO_KHOA
	{
		
		private string _MaChuyenNganh;
		
		private string _TenChuyenNganh;
		
		private string _MaKhoa;
		
		public DM_CHUYENNGANH_THEO_KHOA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenNganh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaChuyenNganh
		{
			get
			{
				return this._MaChuyenNganh;
			}
			set
			{
				if ((this._MaChuyenNganh != value))
				{
					this._MaChuyenNganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuyenNganh", DbType="NVarChar(MAX)")]
		public string TenChuyenNganh
		{
			get
			{
				return this._TenChuyenNganh;
			}
			set
			{
				if ((this._TenChuyenNganh != value))
				{
					this._TenChuyenNganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this._MaKhoa = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_KHOA")]
	public partial class DM_KHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoa;
		
		private string _TenKhoa;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    #endregion
		
		public DM_KHOA()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(MAX)")]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_KHOA_SINHVIEN", Storage="_SINHVIENs", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_KHOA = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_KHOA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_NIENKHOA")]
	public partial class DM_NIENKHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _MaNienKhoa;
		
		private string _TenNienKhoa;
		
		private string _ThoiGienNienKhoa;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMaNienKhoaChanging(string value);
    partial void OnMaNienKhoaChanged();
    partial void OnTenNienKhoaChanging(string value);
    partial void OnTenNienKhoaChanged();
    partial void OnThoiGienNienKhoaChanging(string value);
    partial void OnThoiGienNienKhoaChanged();
    #endregion
		
		public DM_NIENKHOA()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNienKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNienKhoa
		{
			get
			{
				return this._MaNienKhoa;
			}
			set
			{
				if ((this._MaNienKhoa != value))
				{
					this.OnMaNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaNienKhoa = value;
					this.SendPropertyChanged("MaNienKhoa");
					this.OnMaNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNienKhoa", DbType="NVarChar(50)")]
		public string TenNienKhoa
		{
			get
			{
				return this._TenNienKhoa;
			}
			set
			{
				if ((this._TenNienKhoa != value))
				{
					this.OnTenNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenNienKhoa = value;
					this.SendPropertyChanged("TenNienKhoa");
					this.OnTenNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGienNienKhoa", DbType="NVarChar(MAX)")]
		public string ThoiGienNienKhoa
		{
			get
			{
				return this._ThoiGienNienKhoa;
			}
			set
			{
				if ((this._ThoiGienNienKhoa != value))
				{
					this.OnThoiGienNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._ThoiGienNienKhoa = value;
					this.SendPropertyChanged("ThoiGienNienKhoa");
					this.OnThoiGienNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_NIENKHOA_SINHVIEN", Storage="_SINHVIENs", ThisKey="MaNienKhoa", OtherKey="MaNienKhoa")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_NIENKHOA = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_NIENKHOA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINHVIEN")]
	public partial class SINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaSinhVien;
		
		private string _TenSinhVien;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _DiaChi;
		
		private string _NgaySinh;
		
		private string _SDT;
		
		private System.Nullable<int> _MaQueQuan;
		
		private System.Nullable<int> _MaDanToc;
		
		private System.Nullable<int> _MaTonGiao;
		
		private string _HinhAnh;
		
		private string _MaLop;
		
		private string _MaKhoa;
		
		private string _MaNienKhoa;
		
		private string _NguoiTao;
		
		private string _NguoiSua;
		
		private string _NgayTao;
		
		private string _NgaySua;
		
		private System.Nullable<bool> _Isdelete;
		
		private EntityRef<DM_DANTOC> _DM_DANTOC;
		
		private EntityRef<DM_KHOA> _DM_KHOA;
		
		private EntityRef<DM_NIENKHOA> _DM_NIENKHOA;
		
		private EntityRef<DM_QUEQUAN> _DM_QUEQUAN;
		
		private EntityRef<DM_TONGIAO> _DM_TONGIAO;
		
		private EntityRef<LOP> _LOP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaSinhVienChanging(string value);
    partial void OnMaSinhVienChanged();
    partial void OnTenSinhVienChanging(string value);
    partial void OnTenSinhVienChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnMaQueQuanChanging(System.Nullable<int> value);
    partial void OnMaQueQuanChanged();
    partial void OnMaDanTocChanging(System.Nullable<int> value);
    partial void OnMaDanTocChanged();
    partial void OnMaTonGiaoChanging(System.Nullable<int> value);
    partial void OnMaTonGiaoChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnMaNienKhoaChanging(string value);
    partial void OnMaNienKhoaChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiSuaChanging(string value);
    partial void OnNguoiSuaChanged();
    partial void OnNgayTaoChanging(string value);
    partial void OnNgayTaoChanged();
    partial void OnNgaySuaChanging(string value);
    partial void OnNgaySuaChanged();
    partial void OnIsdeleteChanging(System.Nullable<bool> value);
    partial void OnIsdeleteChanged();
    #endregion
		
		public SINHVIEN()
		{
			this._DM_DANTOC = default(EntityRef<DM_DANTOC>);
			this._DM_KHOA = default(EntityRef<DM_KHOA>);
			this._DM_NIENKHOA = default(EntityRef<DM_NIENKHOA>);
			this._DM_QUEQUAN = default(EntityRef<DM_QUEQUAN>);
			this._DM_TONGIAO = default(EntityRef<DM_TONGIAO>);
			this._LOP = default(EntityRef<LOP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSinhVien", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSinhVien
		{
			get
			{
				return this._MaSinhVien;
			}
			set
			{
				if ((this._MaSinhVien != value))
				{
					this.OnMaSinhVienChanging(value);
					this.SendPropertyChanging();
					this._MaSinhVien = value;
					this.SendPropertyChanged("MaSinhVien");
					this.OnMaSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSinhVien", DbType="NVarChar(100)")]
		public string TenSinhVien
		{
			get
			{
				return this._TenSinhVien;
			}
			set
			{
				if ((this._TenSinhVien != value))
				{
					this.OnTenSinhVienChanging(value);
					this.SendPropertyChanging();
					this._TenSinhVien = value;
					this.SendPropertyChanged("TenSinhVien");
					this.OnTenSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NVarChar(50)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQueQuan", DbType="Int")]
		public System.Nullable<int> MaQueQuan
		{
			get
			{
				return this._MaQueQuan;
			}
			set
			{
				if ((this._MaQueQuan != value))
				{
					if (this._DM_QUEQUAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQueQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQueQuan = value;
					this.SendPropertyChanged("MaQueQuan");
					this.OnMaQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanToc", DbType="Int")]
		public System.Nullable<int> MaDanToc
		{
			get
			{
				return this._MaDanToc;
			}
			set
			{
				if ((this._MaDanToc != value))
				{
					if (this._DM_DANTOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDanTocChanging(value);
					this.SendPropertyChanging();
					this._MaDanToc = value;
					this.SendPropertyChanged("MaDanToc");
					this.OnMaDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTonGiao", DbType="Int")]
		public System.Nullable<int> MaTonGiao
		{
			get
			{
				return this._MaTonGiao;
			}
			set
			{
				if ((this._MaTonGiao != value))
				{
					if (this._DM_TONGIAO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._MaTonGiao = value;
					this.SendPropertyChanged("MaTonGiao");
					this.OnMaTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(20)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._DM_KHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNienKhoa", DbType="NVarChar(10)")]
		public string MaNienKhoa
		{
			get
			{
				return this._MaNienKhoa;
			}
			set
			{
				if ((this._MaNienKhoa != value))
				{
					if (this._DM_NIENKHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaNienKhoa = value;
					this.SendPropertyChanged("MaNienKhoa");
					this.OnMaNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(50)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiSua", DbType="NVarChar(50)")]
		public string NguoiSua
		{
			get
			{
				return this._NguoiSua;
			}
			set
			{
				if ((this._NguoiSua != value))
				{
					this.OnNguoiSuaChanging(value);
					this.SendPropertyChanging();
					this._NguoiSua = value;
					this.SendPropertyChanged("NguoiSua");
					this.OnNguoiSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="NVarChar(50)")]
		public string NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySua", DbType="NVarChar(50)")]
		public string NgaySua
		{
			get
			{
				return this._NgaySua;
			}
			set
			{
				if ((this._NgaySua != value))
				{
					this.OnNgaySuaChanging(value);
					this.SendPropertyChanging();
					this._NgaySua = value;
					this.SendPropertyChanged("NgaySua");
					this.OnNgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isdelete", DbType="Bit")]
		public System.Nullable<bool> Isdelete
		{
			get
			{
				return this._Isdelete;
			}
			set
			{
				if ((this._Isdelete != value))
				{
					this.OnIsdeleteChanging(value);
					this.SendPropertyChanging();
					this._Isdelete = value;
					this.SendPropertyChanged("Isdelete");
					this.OnIsdeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_DANTOC_SINHVIEN", Storage="_DM_DANTOC", ThisKey="MaDanToc", OtherKey="MaDanToc", IsForeignKey=true)]
		public DM_DANTOC DM_DANTOC
		{
			get
			{
				return this._DM_DANTOC.Entity;
			}
			set
			{
				DM_DANTOC previousValue = this._DM_DANTOC.Entity;
				if (((previousValue != value) 
							|| (this._DM_DANTOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DM_DANTOC.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._DM_DANTOC.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MaDanToc = value.MaDanToc;
					}
					else
					{
						this._MaDanToc = default(Nullable<int>);
					}
					this.SendPropertyChanged("DM_DANTOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_KHOA_SINHVIEN", Storage="_DM_KHOA", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public DM_KHOA DM_KHOA
		{
			get
			{
				return this._DM_KHOA.Entity;
			}
			set
			{
				DM_KHOA previousValue = this._DM_KHOA.Entity;
				if (((previousValue != value) 
							|| (this._DM_KHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DM_KHOA.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._DM_KHOA.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("DM_KHOA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_NIENKHOA_SINHVIEN", Storage="_DM_NIENKHOA", ThisKey="MaNienKhoa", OtherKey="MaNienKhoa", IsForeignKey=true)]
		public DM_NIENKHOA DM_NIENKHOA
		{
			get
			{
				return this._DM_NIENKHOA.Entity;
			}
			set
			{
				DM_NIENKHOA previousValue = this._DM_NIENKHOA.Entity;
				if (((previousValue != value) 
							|| (this._DM_NIENKHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DM_NIENKHOA.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._DM_NIENKHOA.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MaNienKhoa = value.MaNienKhoa;
					}
					else
					{
						this._MaNienKhoa = default(string);
					}
					this.SendPropertyChanged("DM_NIENKHOA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_QUEQUAN_SINHVIEN", Storage="_DM_QUEQUAN", ThisKey="MaQueQuan", OtherKey="MaQueQuan", IsForeignKey=true)]
		public DM_QUEQUAN DM_QUEQUAN
		{
			get
			{
				return this._DM_QUEQUAN.Entity;
			}
			set
			{
				DM_QUEQUAN previousValue = this._DM_QUEQUAN.Entity;
				if (((previousValue != value) 
							|| (this._DM_QUEQUAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DM_QUEQUAN.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._DM_QUEQUAN.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MaQueQuan = value.MaQueQuan;
					}
					else
					{
						this._MaQueQuan = default(Nullable<int>);
					}
					this.SendPropertyChanged("DM_QUEQUAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_TONGIAO_SINHVIEN", Storage="_DM_TONGIAO", ThisKey="MaTonGiao", OtherKey="MaTonGiao", IsForeignKey=true)]
		public DM_TONGIAO DM_TONGIAO
		{
			get
			{
				return this._DM_TONGIAO.Entity;
			}
			set
			{
				DM_TONGIAO previousValue = this._DM_TONGIAO.Entity;
				if (((previousValue != value) 
							|| (this._DM_TONGIAO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DM_TONGIAO.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._DM_TONGIAO.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MaTonGiao = value.MaTonGiao;
					}
					else
					{
						this._MaTonGiao = default(Nullable<int>);
					}
					this.SendPropertyChanged("DM_TONGIAO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_SINHVIEN", Storage="_LOP", ThisKey="MaLop", OtherKey="MaLop", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MaLop = value.MaLop;
					}
					else
					{
						this._MaLop = default(string);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
