<?xml version="1.0" encoding="utf-8"?><Database Name="data_QLSV" Class="DataQLSVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=data_QLSV;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="data_QLSVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DM_TONGIAO" Member="DM_TONGIAOs">
    <Type Name="DM_TONGIAO">
      <Column Name="MaTonGiao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTonGiao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DM_TONGIAO_SINHVIEN" Member="SINHVIENs" ThisKey="MaTonGiao" OtherKey="MaTonGiao" Type="SINHVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.DM_QUEQUAN" Member="DM_QUEQUANs">
    <Type Name="DM_QUEQUAN">
      <Column Name="MaQueQuan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQueQuan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DM_QUEQUAN_SINHVIEN" Member="SINHVIENs" ThisKey="MaQueQuan" OtherKey="MaQueQuan" Type="SINHVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.DM_DANTOC" Member="DM_DANTOCs">
    <Type Name="DM_DANTOC">
      <Column Name="MaDanToc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanToc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DM_DANTOC_SINHVIEN" Member="SINHVIENs" ThisKey="MaDanToc" OtherKey="MaDanToc" Type="SINHVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.DM_NIENKHOA" Member="DM_NIENKHOAs">
    <Type Name="DM_NIENKHOA">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNienKhoa" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNienKhoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGienNienKhoa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DM_NIENKHOA_SINHVIEN" Member="SINHVIENs" ThisKey="MaNienKhoa" OtherKey="MaNienKhoa" Type="SINHVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.DM_KHOA" Member="DM_KHOAs">
    <Type Name="DM_KHOA">
      <Column Name="MaKhoa" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DM_KHOA_DM_CHUYENNGANH_THEO_KHOA" Member="DM_CHUYENNGANH_THEO_KHOAs" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="DM_CHUYENNGANH_THEO_KHOA" />
    </Type>
  </Table>
  <Table Name="dbo.LOP" Member="LOPs">
    <Type Name="LOP">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaChuyenNganh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MaNienKhoa" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NguoiThem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayThem" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOP_SINHVIEN" Member="SINHVIENs" ThisKey="MaLop" OtherKey="MaLop" Type="SINHVIEN" />
      <Association Name="DM_CHUYENNGANH_THEO_KHOA_LOP" Member="DM_CHUYENNGANH_THEO_KHOA" ThisKey="MaChuyenNganh" OtherKey="MaChuyenNganh" Type="DM_CHUYENNGANH_THEO_KHOA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SINHVIEN" Member="SINHVIENs">
    <Type Name="SINHVIEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSinhVien" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSinhVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="MaQueQuan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDanToc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTonGiao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MaNienKhoa" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Isdelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SINHVIEN_PHANPHONGTHI" Member="PHANPHONGTHIs" ThisKey="MaSinhVien" OtherKey="MaSV" Type="PHANPHONGTHI" />
      <Association Name="DM_DANTOC_SINHVIEN" Member="DM_DANTOC" ThisKey="MaDanToc" OtherKey="MaDanToc" Type="DM_DANTOC" IsForeignKey="true" />
      <Association Name="DM_NIENKHOA_SINHVIEN" Member="DM_NIENKHOA" ThisKey="MaNienKhoa" OtherKey="MaNienKhoa" Type="DM_NIENKHOA" IsForeignKey="true" />
      <Association Name="DM_QUEQUAN_SINHVIEN" Member="DM_QUEQUAN" ThisKey="MaQueQuan" OtherKey="MaQueQuan" Type="DM_QUEQUAN" IsForeignKey="true" />
      <Association Name="DM_TONGIAO_SINHVIEN" Member="DM_TONGIAO" ThisKey="MaTonGiao" OtherKey="MaTonGiao" Type="DM_TONGIAO" IsForeignKey="true" />
      <Association Name="LOP_SINHVIEN" Member="LOP" ThisKey="MaLop" OtherKey="MaLop" Type="LOP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIEM_TBMON" Member="DIEM_TBMONs">
    <Type Name="DIEM_TBMON">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMonHoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaSinhVien" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DiemTBLan1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemTBLan2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DM_MONHOC" Member="DM_MONHOCs">
    <Type Name="DM_MONHOC">
      <Column Name="MaMonHoc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DM_MONHOC_PHANMON_THEO_CHUYENNGANH" Member="PHANMON_THEO_CHUYENNGANHs" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="PHANMON_THEO_CHUYENNGANH" />
    </Type>
  </Table>
  <Table Name="dbo.DM_CHUYENNGANH_THEO_KHOA" Member="DM_CHUYENNGANH_THEO_KHOAs">
    <Type Name="DM_CHUYENNGANH_THEO_KHOA">
      <Column Name="MaChuyenNganh" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenChuyenNganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="DM_CHUYENNGANH_THEO_KHOA_LOP" Member="LOPs" ThisKey="MaChuyenNganh" OtherKey="MaChuyenNganh" Type="LOP" />
      <Association Name="DM_KHOA_DM_CHUYENNGANH_THEO_KHOA" Member="DM_KHOA" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="DM_KHOA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHANMON_THEO_CHUYENNGANH" Member="PHANMON_THEO_CHUYENNGANHs">
    <Type Name="PHANMON_THEO_CHUYENNGANH">
      <Column Name="MaMonTheoChuyenNganh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMonHoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="MaChuyenNganh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaHocKy" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaNienKhoa" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DVHT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHANMON_THEO_CHUYENNGANH_PHANPHONGTHI" Member="PHANPHONGTHIs" ThisKey="MaMonTheoChuyenNganh" OtherKey="MaMonHocTheoChuyenNganh" Type="PHANPHONGTHI" />
      <Association Name="DM_MONHOC_PHANMON_THEO_CHUYENNGANH" Member="DM_MONHOC" ThisKey="MaMonHoc" OtherKey="MaMonHoc" Type="DM_MONHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DM_PHONGTHI" Member="DM_PHONGTHIs">
    <Type Name="DM_PHONGTHI">
      <Column Name="MaPhongThi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DM_PHONGTHI_PHANPHONGTHI" Member="PHANPHONGTHIs" ThisKey="MaPhongThi" OtherKey="MaPhongThi" Type="PHANPHONGTHI" />
    </Type>
  </Table>
  <Table Name="dbo.PHANPHONGTHI" Member="PHANPHONGTHIs">
    <Type Name="PHANPHONGTHI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSV" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaPhongThi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaMonHocTheoChuyenNganh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DM_PHONGTHI_PHANPHONGTHI" Member="DM_PHONGTHI" ThisKey="MaPhongThi" OtherKey="MaPhongThi" Type="DM_PHONGTHI" IsForeignKey="true" />
      <Association Name="PHANMON_THEO_CHUYENNGANH_PHANPHONGTHI" Member="PHANMON_THEO_CHUYENNGANH" ThisKey="MaMonHocTheoChuyenNganh" OtherKey="MaMonTheoChuyenNganh" Type="PHANMON_THEO_CHUYENNGANH" IsForeignKey="true" />
      <Association Name="SINHVIEN_PHANPHONGTHI" Member="SINHVIEN" ThisKey="MaSV" OtherKey="MaSinhVien" Type="SINHVIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>