#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bailam1.Models.LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="data_QLSV")]
	public partial class DataQLSVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLOP(LOP instance);
    partial void UpdateLOP(LOP instance);
    partial void DeleteLOP(LOP instance);
    partial void InsertDM_TONGIAO(DM_TONGIAO instance);
    partial void UpdateDM_TONGIAO(DM_TONGIAO instance);
    partial void DeleteDM_TONGIAO(DM_TONGIAO instance);
    partial void InsertDM_QUEQUAN(DM_QUEQUAN instance);
    partial void UpdateDM_QUEQUAN(DM_QUEQUAN instance);
    partial void DeleteDM_QUEQUAN(DM_QUEQUAN instance);
    partial void InsertDM_DANTOC(DM_DANTOC instance);
    partial void UpdateDM_DANTOC(DM_DANTOC instance);
    partial void DeleteDM_DANTOC(DM_DANTOC instance);
    partial void InsertDM_KHOA(DM_KHOA instance);
    partial void UpdateDM_KHOA(DM_KHOA instance);
    partial void DeleteDM_KHOA(DM_KHOA instance);
    partial void InsertDM_NIENKHOA(DM_NIENKHOA instance);
    partial void UpdateDM_NIENKHOA(DM_NIENKHOA instance);
    partial void DeleteDM_NIENKHOA(DM_NIENKHOA instance);
    #endregion
		
		public DataQLSVDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["data_QLSVConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLSVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLSVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLSVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLSVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LOP> LOPs
		{
			get
			{
				return this.GetTable<LOP>();
			}
		}
		
		public System.Data.Linq.Table<DM_TONGIAO> DM_TONGIAOs
		{
			get
			{
				return this.GetTable<DM_TONGIAO>();
			}
		}
		
		public System.Data.Linq.Table<DM_QUEQUAN> DM_QUEQUANs
		{
			get
			{
				return this.GetTable<DM_QUEQUAN>();
			}
		}
		
		public System.Data.Linq.Table<DM_DANTOC> DM_DANTOCs
		{
			get
			{
				return this.GetTable<DM_DANTOC>();
			}
		}
		
		public System.Data.Linq.Table<DM_CHUYENNGANH_THEO_KHOA> DM_CHUYENNGANH_THEO_KHOAs
		{
			get
			{
				return this.GetTable<DM_CHUYENNGANH_THEO_KHOA>();
			}
		}
		
		public System.Data.Linq.Table<DM_KHOA> DM_KHOAs
		{
			get
			{
				return this.GetTable<DM_KHOA>();
			}
		}
		
		public System.Data.Linq.Table<DM_NIENKHOA> DM_NIENKHOAs
		{
			get
			{
				return this.GetTable<DM_NIENKHOA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOP")]
	public partial class LOP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaLop;
		
		private string _TenLop;
		
		private string _MaChuyenNganh;
		
		private string _MaKhoa;
		
		private string _MaNienKhoa;
		
		private string _NguoiThem;
		
		private string _NguoiSua;
		
		private System.Nullable<System.DateTime> _NgayThem;
		
		private System.Nullable<System.DateTime> _NgaySua;
		
		private System.Nullable<bool> _IsDelete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    partial void OnMaChuyenNganhChanging(string value);
    partial void OnMaChuyenNganhChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnMaNienKhoaChanging(string value);
    partial void OnMaNienKhoaChanged();
    partial void OnNguoiThemChanging(string value);
    partial void OnNguoiThemChanged();
    partial void OnNguoiSuaChanging(string value);
    partial void OnNguoiSuaChanged();
    partial void OnNgayThemChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThemChanged();
    partial void OnNgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySuaChanged();
    partial void OnIsDeleteChanging(System.Nullable<bool> value);
    partial void OnIsDeleteChanged();
    #endregion
		
		public LOP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(MAX)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenNganh", DbType="NVarChar(10)")]
		public string MaChuyenNganh
		{
			get
			{
				return this._MaChuyenNganh;
			}
			set
			{
				if ((this._MaChuyenNganh != value))
				{
					this.OnMaChuyenNganhChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenNganh = value;
					this.SendPropertyChanged("MaChuyenNganh");
					this.OnMaChuyenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNienKhoa", DbType="NVarChar(10)")]
		public string MaNienKhoa
		{
			get
			{
				return this._MaNienKhoa;
			}
			set
			{
				if ((this._MaNienKhoa != value))
				{
					this.OnMaNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaNienKhoa = value;
					this.SendPropertyChanged("MaNienKhoa");
					this.OnMaNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThem", DbType="NVarChar(50)")]
		public string NguoiThem
		{
			get
			{
				return this._NguoiThem;
			}
			set
			{
				if ((this._NguoiThem != value))
				{
					this.OnNguoiThemChanging(value);
					this.SendPropertyChanging();
					this._NguoiThem = value;
					this.SendPropertyChanged("NguoiThem");
					this.OnNguoiThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiSua", DbType="NVarChar(50)")]
		public string NguoiSua
		{
			get
			{
				return this._NguoiSua;
			}
			set
			{
				if ((this._NguoiSua != value))
				{
					this.OnNguoiSuaChanging(value);
					this.SendPropertyChanging();
					this._NguoiSua = value;
					this.SendPropertyChanged("NguoiSua");
					this.OnNguoiSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThem", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThem
		{
			get
			{
				return this._NgayThem;
			}
			set
			{
				if ((this._NgayThem != value))
				{
					this.OnNgayThemChanging(value);
					this.SendPropertyChanging();
					this._NgayThem = value;
					this.SendPropertyChanged("NgayThem");
					this.OnNgayThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySua
		{
			get
			{
				return this._NgaySua;
			}
			set
			{
				if ((this._NgaySua != value))
				{
					this.OnNgaySuaChanging(value);
					this.SendPropertyChanging();
					this._NgaySua = value;
					this.SendPropertyChanged("NgaySua");
					this.OnNgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit")]
		public System.Nullable<bool> IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this.OnIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsDelete = value;
					this.SendPropertyChanged("IsDelete");
					this.OnIsDeleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_TONGIAO")]
	public partial class DM_TONGIAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTonGiao;
		
		private string _TenTonGiao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTonGiaoChanging(int value);
    partial void OnMaTonGiaoChanged();
    partial void OnTenTonGiaoChanging(string value);
    partial void OnTenTonGiaoChanged();
    #endregion
		
		public DM_TONGIAO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTonGiao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTonGiao
		{
			get
			{
				return this._MaTonGiao;
			}
			set
			{
				if ((this._MaTonGiao != value))
				{
					this.OnMaTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._MaTonGiao = value;
					this.SendPropertyChanged("MaTonGiao");
					this.OnMaTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTonGiao", DbType="NVarChar(MAX)")]
		public string TenTonGiao
		{
			get
			{
				return this._TenTonGiao;
			}
			set
			{
				if ((this._TenTonGiao != value))
				{
					this.OnTenTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TenTonGiao = value;
					this.SendPropertyChanged("TenTonGiao");
					this.OnTenTonGiaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_QUEQUAN")]
	public partial class DM_QUEQUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQueQuan;
		
		private string _TenQueQuan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQueQuanChanging(int value);
    partial void OnMaQueQuanChanged();
    partial void OnTenQueQuanChanging(string value);
    partial void OnTenQueQuanChanged();
    #endregion
		
		public DM_QUEQUAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQueQuan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaQueQuan
		{
			get
			{
				return this._MaQueQuan;
			}
			set
			{
				if ((this._MaQueQuan != value))
				{
					this.OnMaQueQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQueQuan = value;
					this.SendPropertyChanged("MaQueQuan");
					this.OnMaQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQueQuan", DbType="NVarChar(MAX)")]
		public string TenQueQuan
		{
			get
			{
				return this._TenQueQuan;
			}
			set
			{
				if ((this._TenQueQuan != value))
				{
					this.OnTenQueQuanChanging(value);
					this.SendPropertyChanging();
					this._TenQueQuan = value;
					this.SendPropertyChanged("TenQueQuan");
					this.OnTenQueQuanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_DANTOC")]
	public partial class DM_DANTOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanToc;
		
		private string _TenDanToc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanTocChanging(int value);
    partial void OnMaDanTocChanged();
    partial void OnTenDanTocChanging(string value);
    partial void OnTenDanTocChanged();
    #endregion
		
		public DM_DANTOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanToc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanToc
		{
			get
			{
				return this._MaDanToc;
			}
			set
			{
				if ((this._MaDanToc != value))
				{
					this.OnMaDanTocChanging(value);
					this.SendPropertyChanging();
					this._MaDanToc = value;
					this.SendPropertyChanged("MaDanToc");
					this.OnMaDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanToc", DbType="NVarChar(MAX)")]
		public string TenDanToc
		{
			get
			{
				return this._TenDanToc;
			}
			set
			{
				if ((this._TenDanToc != value))
				{
					this.OnTenDanTocChanging(value);
					this.SendPropertyChanging();
					this._TenDanToc = value;
					this.SendPropertyChanged("TenDanToc");
					this.OnTenDanTocChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_CHUYENNGANH_THEO_KHOA")]
	public partial class DM_CHUYENNGANH_THEO_KHOA
	{
		
		private string _MaChuyenNganh;
		
		private string _TenChuyenNganh;
		
		private string _MaKhoa;
		
		public DM_CHUYENNGANH_THEO_KHOA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenNganh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaChuyenNganh
		{
			get
			{
				return this._MaChuyenNganh;
			}
			set
			{
				if ((this._MaChuyenNganh != value))
				{
					this._MaChuyenNganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuyenNganh", DbType="NVarChar(MAX)")]
		public string TenChuyenNganh
		{
			get
			{
				return this._TenChuyenNganh;
			}
			set
			{
				if ((this._TenChuyenNganh != value))
				{
					this._TenChuyenNganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this._MaKhoa = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_KHOA")]
	public partial class DM_KHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoa;
		
		private string _TenKhoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    #endregion
		
		public DM_KHOA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(MAX)")]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_NIENKHOA")]
	public partial class DM_NIENKHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _MaNienKhoa;
		
		private string _TenNienKhoa;
		
		private string _ThoiGienNienKhoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMaNienKhoaChanging(string value);
    partial void OnMaNienKhoaChanged();
    partial void OnTenNienKhoaChanging(string value);
    partial void OnTenNienKhoaChanged();
    partial void OnThoiGienNienKhoaChanging(string value);
    partial void OnThoiGienNienKhoaChanged();
    #endregion
		
		public DM_NIENKHOA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNienKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNienKhoa
		{
			get
			{
				return this._MaNienKhoa;
			}
			set
			{
				if ((this._MaNienKhoa != value))
				{
					this.OnMaNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaNienKhoa = value;
					this.SendPropertyChanged("MaNienKhoa");
					this.OnMaNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNienKhoa", DbType="NVarChar(50)")]
		public string TenNienKhoa
		{
			get
			{
				return this._TenNienKhoa;
			}
			set
			{
				if ((this._TenNienKhoa != value))
				{
					this.OnTenNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenNienKhoa = value;
					this.SendPropertyChanged("TenNienKhoa");
					this.OnTenNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGienNienKhoa", DbType="NVarChar(MAX)")]
		public string ThoiGienNienKhoa
		{
			get
			{
				return this._ThoiGienNienKhoa;
			}
			set
			{
				if ((this._ThoiGienNienKhoa != value))
				{
					this.OnThoiGienNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._ThoiGienNienKhoa = value;
					this.SendPropertyChanged("ThoiGienNienKhoa");
					this.OnThoiGienNienKhoaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
